### ISSUE TITLE
[BUG] attempt to index local 'vignetteInfo' (a nil value)

### ISSUE THREAD

**Issue by Slackluster** [Dathwada/handynotes-travelguide#58] opened 2024-12-18 18:14 UTC
**Describe the bug**
8x ...zard_SharedMapDataProviders/VignetteDataProvider.lua:14: attempt to index local 'vignetteInfo' (a nil value)
[string "@Blizzard_SharedMapDataProviders/VignetteDataProvider.lua"]:14: in function `GetPinTemplate'
[string "@HandyNotes_TravelGuide/core/handler.lua"]:116: in main chunk

**To Reproduce**
Log in.

**Expected behavior**
No error.

**Screenshots**
N/A

**More infos (please complete the following information):**
The Blizz API changed and the vignette thing now requires another argument, or so I gathered.

**Comment by Dathwada** [comment] 2024-12-18 18:18
duplicate of #56

I just released v2.21.0, it is available here on [GitHub](https://github.com/Dathwada/handynotes-travelguide/releases/tag/Retail-v2.21.0) and should be available on [CurseForge](https://legacy.curseforge.com/wow/addons/handynotes-travelguide/files/6002677) or [Wago](https://addons.wago.io/addons/handynotes-travelguide/versions?stability=stable) in a few minutes.

Please update to the new version, this should fix this lua error.

**Closed by Dathwada** 2024-12-18 18:18 UTC
Labels: bug, duplicate
