### ISSUE TITLE
[LUA Errors Patch 11.0.7]

### ISSUE THREAD

**Issue by JesperLive** [Dathwada/handynotes-travelguide#57] opened 2024-12-18 11:46 UTC
**Describe the bug**
Getting a few LUA errors

**To Reproduce**
Log in to the world

**Expected behavior**
No errors

**More infos (please complete the following information):**
 - Version V2.20.0
 - Client Retails

**Additional context**

[LUA Error 1](https://pastecode.io/s/vaowubjh)
[LUA Error 2](https://pastecode.io/s/k20818p9)

**Comment by Dathwada** [comment] 2024-12-18 16:43
duplicate of #56

**Closed by Dathwada** 2024-12-18 16:43 UTC
Labels: bug, duplicate
